version: '3.3'
services:
  web:
    build:
      context: ../source
      dockerfile: Dockerfile
    image: php:7.3-apache
    container_name: php73
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - 8081:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
